from API.MenuBar.Edit.EditConst import EditConst
from API.MenuBar.Edit.Edit import Edit
from API.Utility.Util import Util
from API.Utility import UtilConst
from API.ComponentBox import ComponentBoxConst
from API.Device.Router.Router import Router

from API.Device.EndDevice.PC.PC import PC

from API.Toolbar.CommonToolsBar.CommonToolsBar import CommonToolsBar
from API.Toolbar.MainToolBar.MainToolbarConst import MainToolbarConst
from API.MenuBar.File.New.NewConst import NewConst
util = Util()
editMenu = Edit()
commonToolsBar = CommonToolsBar()

CopyRouter0 = Router(ComponentBoxConst.DeviceModel.CUSTOM_1841, 100, 50, "CopyRouter0")
CopyRouter1 = Router(ComponentBoxConst.DeviceModel.CUSTOM_2621XM, 200, 50, "CopyRouter1")
CopyRouter2 = Router(ComponentBoxConst.DeviceModel.CUSTOM_2811,300, 50, "CopyRouter2")
CopyPC0 = PC(ComponentBoxConst.DeviceModel.CUSTOM_WIRELESS_PC,400, 50, "CopyPC0")


Router0 = Router(ComponentBoxConst.DeviceModel.CUSTOM_1841, 100, 100, "Router0")
Router1 = Router(ComponentBoxConst.DeviceModel.CUSTOM_2621XM, 200, 100, "Router1")
Router2 = Router(ComponentBoxConst.DeviceModel.CUSTOM_2811,300, 100, "Router2")
PC0 = PC(ComponentBoxConst.DeviceModel.CUSTOM_WIRELESS_PC, 400, 100, "PC0")

def main():
    util.init()
    copyPaste_deviceOnWorkspace()

def copyPaste_deviceOnWorkspace():
    util.createDevice(ComponentBoxConst.DeviceType.MISCELLANEOUS, Router0.model, Router0.x, Router0.y)    
    util.createDevice(ComponentBoxConst.DeviceType.MISCELLANEOUS, Router1.model, Router1.x, Router1.y)    
    util.createDevice(ComponentBoxConst.DeviceType.MISCELLANEOUS, PC0.model, PC0.x, PC0.y) 
    util.createDevice(ComponentBoxConst.DeviceType.MISCELLANEOUS, Router2.model, Router2.x, Router2.y)   
    
    util.clickOnSimulation()
    util.clickOnRealtime()
    util.clickOnWorkspace(Router0.x, Router0.y)
    Router0.select()
    Router0.clickConfigTab()
    Router0.config.settings.hostname("RouterCopy")
    Router0.config.selectInterface('Static')
    Router0.config.routing.static.addRoute("10.0.0.0", "255.0.0.0", "10.1.1.1")
    Router0.config.selectInterface('RIP')
    Router0.config.routing.rip.addRoute("10.0.0.0")
    Router0.config.selectInterface("FastEthernet0/0")
    Router0.config.interface.ethernet.ip("10.1.1.2")
    Router0.config.interface.ethernet.subnet("255.0.0.0")
    Router0.config.interface.ethernet.bandwidth('Auto')
    Router0.config.interface.ethernet.duplex('Auto')
    Router0.config.interface.ethernet.portStatus(True)
    Router0.close()
    
    Router1.select()
    Router1.clickConfigTab()
    Router1.config.settings.hostname("RouterCopy")
    Router1.config.selectInterface('Static')
    Router1.config.routing.static.addRoute("10.0.0.0", "255.0.0.0", "10.1.1.1")
    Router1.config.selectInterface('RIP')
    Router1.config.routing.rip.addRoute("10.0.0.0")
    Router1.config.selectInterface("FastEthernet0/0")
    Router1.config.interface.ethernet.ip("10.1.1.2")
    Router1.config.interface.ethernet.subnet("255.0.0.0")  
    Router1.config.interface.ethernet.bandwidth('Auto')
    Router1.config.interface.ethernet.duplex('Auto')
    Router1.config.interface.ethernet.portStatus(True)
    Router1.close()
    
    Router2.select()
    Router2.clickConfigTab()
    Router2.config.settings.hostname("RouterCopy")
    Router2.config.selectInterface('Static')
    Router2.config.routing.static.addRoute("10.0.0.0", "255.0.0.0", "10.1.1.1")
    Router2.config.selectInterface('RIP')
    Router2.config.routing.rip.addRoute("10.0.0.0")
    Router2.config.selectInterface("FastEthernet0/0")
    Router2.config.interface.ethernet.ip("10.1.1.2")
    Router2.config.interface.ethernet.subnet("255.0.0.0")     
    Router2.config.interface.ethernet.bandwidth('Auto')
    Router2.config.interface.ethernet.duplex('Auto')
    Router2.config.interface.ethernet.portStatus(True)
    Router2.close()
    
    PC0.select()
    PC0.clickConfigTab()
    PC0.config.selectInterface("Wireless0")
    PC0.config.interface.wireless.ssid("LinksysRouter")
    PC0.config.interface.wireless.wep()   
    while (object.exists(UtilConst.ERROR_MESSAGE_OK)):
        util.clickButton(UtilConst.ERROR_MESSAGE_OK)
    PC0.config.interface.wireless.wepkey("0123456789")   
    PC0.close()

    util.selectObjectsOnWorkspace(Router0.x, Router0.y)

    util.selectObjectsOnWorkspace(Router1.x, Router1.y)
    util.selectObjectsOnWorkspace(Router2.x, Router2.y)
    util.selectObjectsOnWorkspace(PC0.x, PC0.y)
    snooze(2)
    editMenu.selectEditItem(EditConst.COPY)
    editMenu.selectEditItem(EditConst.PASTE)

    CopyRouter0.select()
    CopyRouter0.clickConfigTab()
    CopyRouter0.config.settings.check.hostname("RouterCopy")
    CopyRouter0.config.settings.check.displayName("CopyRouter0")
    CopyRouter0.config.selectInterface('Static')
    CopyRouter0.config.routing.static.removeRow(0)
    CopyRouter0.config.selectInterface('RIP')
    CopyRouter0.config.routing.rip.removeRow(0)
    CopyRouter0.cli.textCheckPoint("no ip route 10.0.0.0 255.0.0.0 10.1.1.1")       
    CopyRouter0.cli.textCheckPoint("no network 10.0.0.0")
    CopyRouter0.config.selectInterface("FastEthernet0/0")
    CopyRouter0.config.interface.ethernet.check.ip("10.1.1.2")
    CopyRouter0.config.interface.ethernet.check.subnet("255.0.0.0")
    CopyRouter0.config.interface.ethernet.check.bandwidth('Auto', True)
    CopyRouter0.config.interface.ethernet.check.duplex('Auto', True)
    CopyRouter0.config.interface.ethernet.check.portStatus(True)
    CopyRouter0.close()
    
    CopyRouter1.select()
    CopyRouter1.clickConfigTab()
    CopyRouter1.config.settings.check.hostname("RouterCopy")
    CopyRouter1.config.settings.check.displayName("CopyRouter1")
    CopyRouter1.config.selectInterface('Static')
    CopyRouter1.config.routing.static.removeRow(0)
    CopyRouter1.config.selectInterface('RIP')
    CopyRouter1.config.routing.rip.removeRow(0)
    CopyRouter1.cli.textCheckPoint("no ip route 10.0.0.0 255.0.0.0 10.1.1.1")       
    CopyRouter1.cli.textCheckPoint("no network 10.0.0.0")
    CopyRouter1.config.selectInterface("FastEthernet0/0")
    CopyRouter1.config.interface.ethernet.check.ip("10.1.1.2")
    CopyRouter1.config.interface.ethernet.check.subnet("255.0.0.0")
    CopyRouter1.config.interface.ethernet.check.bandwidth('Auto', True)
    CopyRouter1.config.interface.ethernet.check.duplex('Auto', True)
    CopyRouter1.config.interface.ethernet.check.portStatus(True)
    CopyRouter1.close()
    
    CopyRouter2.select()
    CopyRouter2.clickConfigTab()
    CopyRouter2.config.settings.check.hostname("RouterCopy")
    CopyRouter2.config.settings.check.displayName("CopyRouter2")
    CopyRouter2.config.selectInterface('Static')
    CopyRouter2.config.routing.static.removeRow(0)
    CopyRouter2.config.selectInterface('RIP')
    CopyRouter2.config.routing.rip.removeRow(0)
    CopyRouter2.cli.textCheckPoint("no ip route 10.0.0.0 255.0.0.0 10.1.1.1")       
    CopyRouter2.cli.textCheckPoint("no network 10.0.0.0")
    CopyRouter2.config.selectInterface("FastEthernet0/0")
    CopyRouter2.config.interface.ethernet.check.ip("10.1.1.2")
    CopyRouter2.config.interface.ethernet.check.subnet("255.0.0.0")
    CopyRouter2.config.interface.ethernet.check.bandwidth('Auto', True)
    CopyRouter2.config.interface.ethernet.check.duplex('Auto', True)
    CopyRouter2.config.interface.ethernet.check.portStatus(True)
    CopyRouter2.close()
    
    CopyPC0.select()
    CopyPC0.clickConfigTab()
    CopyPC0.config.settings.check.displayName("CopyPC0")
    CopyPC0.config.selectInterface("Wireless0") 
    CopyPC0.config.interface.wireless.check.ssid("LinksysRouter")
    CopyPC0.config.interface.wireless.check.wepkey("0123456789")
    CopyPC0.close()
