class DrawShapesConst:
	SHAPE_TYPES = ':shapeOptions_shapeType_HTML_Object'
	RECTANGLE = ':Rectangle_HTML_Object'
	ELLIPSE = ':Ellipse_HTML_Object'
	LINE = ':Line_HTML_Object'
	FILL_ENABLED = ':shapeOptions_fillEnabled_HTML_Object'
	FILL_COLOR = ':shapeOptions_fillColor_HTML_Object'
	COLOR_RED = ':Red_HTML_Object'
	COLOR_GREEN = ':Green_HTML_Object'
	COLOR_BLUE = ':Blue_HTML_Object'
	COLOR_YELLOW = '::Yellow_HTML_Object'
	COLOR_ORANGE = ':Orange_HTML_Object'
	COLOR_INDIGO = ':Indigo_HTML_Object'
	COLOR_BLACK = ':Black_HTML_Object'
	COLOR_WHITE = ':White_HTML_Object'
	OUTLINE_ENABLED = ':shapeOptions_outlineEnabled_HTML_Object'
	OUTLINE_COLOR = ':shapeOptions_outlineColor_HTML_Object'
	HIDE_OPTIONS = ':shapeOptions_hide_HTML_Object'
	pass