#Thi
from API.ComponentBox import ComponentBoxConst
from API.Device.LinksysRouter.LinksysRouter import LinksysRouter
from API.Device.EndDevice.PC.PC import PC
from API.Utility.Util import Util
from API.Utility.Util import UtilConst
from API.Device.DeviceBase.DesktopBase.DesktopBaseConst import DesktopConst
import os

#Function initialization
util = Util()

#Device initialization
Linksys_WMP300N = PC(ComponentBoxConst.DeviceModel.CUSTOM_WIRELESS_PC, 445, 115, "Linksys_WMP300N")
PC_BG = PC(ComponentBoxConst.DeviceModel.CUSTOM_WIRELESS_PC, 445, 214, "PC_BG")
PC_A = PC(ComponentBoxConst.DeviceModel.CUSTOM_WIRELESS_PC, 450, 312, "PC_A")
Tablet_PC2 = PC(ComponentBoxConst.DeviceModel.CUSTOM_WIRELESS_PC, 447, 42, "Tablet PC2")
Pda1 = PC(ComponentBoxConst.DeviceModel.CUSTOM_WIRELESS_PC, 147, 312, "Pda1")
wirelessRouter0 = LinksysRouter(ComponentBoxConst.DeviceModel.LINKSYS, 171, 144, "Wireless Router0")

def main():
    createTopology()
    basicWirelessSettings_Mixed()
    basicWirelessSettings_BGMixed()
    basicWirelessSettings_BOnly()
    basicWirelessSettings_GOnly()
    basicWirelessSettings_Disabled()
    basicWirelessSettings_NOnly()   
    disableSSIDBroadcast()
    
def createTopology():
    #a.    Create and connect devices according to diagram.
    #a.    On PC0, remove ethernet interface and insert Linksys WRT-300N.
    util.open("UI53_Linksys.pkt", UtilConst.UI_TEST)

def basicWirelessSettings_Mixed():
    wirelessRouter0.select()
    wirelessRouter0.clickGuiTab()
    wirelessRouter0.gui.tabs.wireless()
    wirelessRouter0.gui.wireless.basicWirelessSettings.networkMode("Mixed")
    wirelessRouter0.gui.wireless.basicWirelessSettings.radioBand("Auto")
    wirelessRouter0.gui.wireless.basicWirelessSettings.standardChannel("9 - 2\\.452GHz")
    wirelessRouter0.gui.wireless.basicWirelessSettings.saveSettingsButton()
    wirelessRouter0.close()
    
    Linksys_WMP300N.select()
    Linksys_WMP300N.clickDesktopTab()
    Linksys_WMP300N.desktop.applications.pcWireless()
    Linksys_WMP300N.desktop.pcWireless.tabs.connect()
    snooze(15)
    Linksys_WMP300N.desktop.pcWireless.connect.check.siteNetworkType("Mixed B/G/N")
    Linksys_WMP300N.desktop.pcWireless.connect.check.siteRadioBand("Auto")
    util.fastForwardTime()
    snooze(5)
    test.compare(findObject(Linksys_WMP300N.squishName + DesktopConst.pcwireless.connectTab.NETWORK_TABLE).rowCount, 1)
    Linksys_WMP300N.desktop.applications.commandPrompt()
    Linksys_WMP300N.desktop.commandPrompt.setText("ping 192.168.0.1")
    util.speedUpConvergence()
    Linksys_WMP300N.desktop.commandPrompt.textCheckPoint("Received = 0", 0)
    Linksys_WMP300N.close()

    PC_BG.select()
    PC_BG.clickDesktopTab()
    PC_BG.desktop.applications.commandPrompt()
    PC_BG.desktop.commandPrompt.setText("ping 192.168.0.1")
    util.speedUpConvergence()
    PC_BG.desktop.commandPrompt.textCheckPoint("Received = 0", 0)
    PC_BG.close()
    
    PC_A.select()
    PC_A.clickDesktopTab()
    PC_A.desktop.applications.commandPrompt()
    PC_A.desktop.commandPrompt.setText("ping 192.168.0.1")
    util.speedUpConvergence()
    PC_A.desktop.commandPrompt.textCheckPoint("Received = 0", 1)
    PC_A.close()
    
    Tablet_PC2.select()
    Tablet_PC2.clickDesktopTab()
    Tablet_PC2.desktop.applications.commandPrompt()
    Tablet_PC2.desktop.commandPrompt.setText("ping 192.168.0.1")
    util.speedUpConvergence()
    Tablet_PC2.desktop.commandPrompt.textCheckPoint("Received = 0", 0)
    Tablet_PC2.close()
    
    Pda1.select()
    Pda1.clickDesktopTab()
    Pda1.desktop.applications.commandPrompt()
    Pda1.desktop.commandPrompt.setText("ping 192.168.0.1")
    util.speedUpConvergence()
    Pda1.desktop.commandPrompt.textCheckPoint("Received = 0", 0)
    Pda1.close()

def basicWirelessSettings_BGMixed():
    wirelessRouter0.select()
    wirelessRouter0.gui.tabs.wireless()
    wirelessRouter0.gui.wireless.basicWirelessSettings.networkMode("BG-Mixed")
    wirelessRouter0.gui.wireless.basicWirelessSettings.standardChannel("4 - 2\\.427GHz")
    wirelessRouter0.gui.wireless.basicWirelessSettings.saveSettingsButton()
    wirelessRouter0.close()
    
    Linksys_WMP300N.select()
    Linksys_WMP300N.desktop.applications.pcWireless()
    Linksys_WMP300N.desktop.pcWireless.tabs.connect()
    Linksys_WMP300N.desktop.pcWireless.connect.refreshButton()
    snooze(5)
    Linksys_WMP300N.desktop.pcWireless.connect.connectButton()
    snooze(10)
    Linksys_WMP300N.desktop.pcWireless.connect.check.siteNetworkType("Mixed B/G")
    Linksys_WMP300N.desktop.pcWireless.connect.check.siteRadioBand("20MHz")
    util.fastForwardTime()
    snooze(5)
    test.compare(findObject(Linksys_WMP300N.squishName + DesktopConst.pcwireless.connectTab.NETWORK_TABLE).rowCount, 1)
    Linksys_WMP300N.desktop.applications.commandPrompt()
    Linksys_WMP300N.desktop.commandPrompt.setText("ping 192.168.0.1")
    util.speedUpConvergence()
    Linksys_WMP300N.desktop.commandPrompt.textCheckPoint("Received = 0", 0)
    Linksys_WMP300N.close()
    
    PC_BG.select()
    PC_BG.desktop.applications.commandPrompt()
    PC_BG.desktop.commandPrompt.setText("ping 192.168.0.1")
    util.speedUpConvergence()
    PC_BG.desktop.commandPrompt.textCheckPoint("Received = 0", 0)
    PC_BG.close()
    
    Tablet_PC2.select()
    Tablet_PC2.desktop.applications.commandPrompt()
    Tablet_PC2.desktop.commandPrompt.setText("ping 192.168.0.1")
    util.speedUpConvergence()
    Tablet_PC2.desktop.commandPrompt.textCheckPoint("Received = 0", 0)
    Tablet_PC2.close()
    
    Pda1.select()
    Pda1.desktop.applications.commandPrompt()
    Pda1.desktop.commandPrompt.setText("ping 192.168.0.1")
    util.speedUpConvergence()
    Pda1.desktop.commandPrompt.textCheckPoint("Received = 0", 0)
    Pda1.close()
    
def basicWirelessSettings_BOnly():
    wirelessRouter0.select()
    wirelessRouter0.gui.tabs.wireless()
    wirelessRouter0.gui.wireless.basicWirelessSettings.networkMode("Wireless-B Only")
    wirelessRouter0.gui.wireless.basicWirelessSettings.saveSettingsButton()
    wirelessRouter0.close()
    
    Linksys_WMP300N.select()
    Linksys_WMP300N.desktop.applications.pcWireless()
    Linksys_WMP300N.desktop.pcWireless.tabs.connect()
    Linksys_WMP300N.desktop.pcWireless.connect.refreshButton()
    snooze(5)
    Linksys_WMP300N.desktop.pcWireless.connect.check.siteNetworkType("Wireless-B")
    Linksys_WMP300N.desktop.pcWireless.connect.check.siteRadioBand("20MHz")
    util.fastForwardTime()
    snooze(5)
    test.compare(findObject(Linksys_WMP300N.squishName + DesktopConst.pcwireless.connectTab.NETWORK_TABLE).rowCount, 1)
    Linksys_WMP300N.close()
    Linksys_WMP300N.select()
    Linksys_WMP300N.clickDesktopTab()
    Linksys_WMP300N.desktop.applications.commandPrompt()
    Linksys_WMP300N.desktop.commandPrompt.setText("ping 192.168.0.1")
    util.speedUpConvergence()
    Linksys_WMP300N.desktop.commandPrompt.textCheckPoint("Received = 0", 0)
    Linksys_WMP300N.close()
    
    PC_BG.select()
    PC_BG.desktop.applications.commandPrompt()
    PC_BG.desktop.commandPrompt.setText("ping 192.168.0.1")
    util.speedUpConvergence()
    PC_BG.desktop.commandPrompt.textCheckPoint("Received = 0", 0)
    PC_BG.close()

    Tablet_PC2.select()
    Tablet_PC2.desktop.applications.commandPrompt()
    Tablet_PC2.desktop.commandPrompt.setText("ping 192.168.0.1")
    util.speedUpConvergence()
    Tablet_PC2.desktop.commandPrompt.textCheckPoint("Received = 0", 0)
    Tablet_PC2.close()
    
    Pda1.select()
    Pda1.desktop.applications.commandPrompt()
    Pda1.desktop.commandPrompt.setText("ping 192.168.0.1")
    util.speedUpConvergence()
    Pda1.desktop.commandPrompt.textCheckPoint("Received = 0", 0)
    Pda1.close()
    
def basicWirelessSettings_GOnly():
    wirelessRouter0.select()
    wirelessRouter0.gui.tabs.wireless()
    wirelessRouter0.gui.wireless.basicWirelessSettings.networkMode("Wireless-G Only")
    wirelessRouter0.gui.wireless.basicWirelessSettings.saveSettingsButton()
    wirelessRouter0.close()
    
    Linksys_WMP300N.select()
    Linksys_WMP300N.desktop.applications.pcWireless()
    Linksys_WMP300N.desktop.pcWireless.tabs.connect()
    Linksys_WMP300N.desktop.pcWireless.connect.refreshButton()
    snooze(5)
    Linksys_WMP300N.desktop.pcWireless.connect.check.siteNetworkType("Wireless-G")
    Linksys_WMP300N.desktop.pcWireless.connect.check.siteRadioBand("20MHz")
    util.fastForwardTime()
    snooze(5)
    test.compare(findObject(Linksys_WMP300N.squishName + DesktopConst.pcwireless.connectTab.NETWORK_TABLE).rowCount, 1)
    Linksys_WMP300N.desktop.applications.commandPrompt()
    Linksys_WMP300N.desktop.commandPrompt.setText("ping 192.168.0.1")
    util.speedUpConvergence()
    Linksys_WMP300N.desktop.commandPrompt.textCheckPoint("Received = 0", 0)
    Linksys_WMP300N.close()
    
    PC_BG.select()
    PC_BG.desktop.applications.commandPrompt()
    PC_BG.desktop.commandPrompt.setText("ping 192.168.0.1")
    util.speedUpConvergence()
    PC_BG.desktop.commandPrompt.textCheckPoint("Received = 0", 0)
    PC_BG.close()
    
    Tablet_PC2.select()
    Tablet_PC2.desktop.applications.commandPrompt()
    Tablet_PC2.desktop.commandPrompt.setText("ping 192.168.0.1")
    util.speedUpConvergence()
    Tablet_PC2.desktop.commandPrompt.textCheckPoint("Received = 0", 0)
    Tablet_PC2.close()
    
    Pda1.select()
    Pda1.desktop.applications.commandPrompt()
    Pda1.desktop.commandPrompt.setText("ping 192.168.0.1")
    util.speedUpConvergence()
    Pda1.desktop.commandPrompt.textCheckPoint("Received = 0", 0)
    Pda1.close()
    
def basicWirelessSettings_Disabled():
    wirelessRouter0.select()
    wirelessRouter0.gui.tabs.wireless()
    wirelessRouter0.gui.wireless.basicWirelessSettings.networkMode("Disabled")
    wirelessRouter0.gui.wireless.basicWirelessSettings.saveSettingsButton()
    Linksys_WMP300N.select()
    Linksys_WMP300N.desktop.applications.pcWireless()
    Linksys_WMP300N.desktop.pcWireless.tabs.connect()
    Linksys_WMP300N.desktop.pcWireless.connect.refreshButton()
    snooze(5)
    test.compare(findObject(Linksys_WMP300N.squishName + DesktopConst.pcwireless.connectTab.NETWORK_TABLE).rowCount, 1)
    Linksys_WMP300N.desktop.applications.commandPrompt()
    Linksys_WMP300N.desktop.commandPrompt.setText("ping 192.168.0.1")
    util.speedUpConvergence()
    Linksys_WMP300N.desktop.commandPrompt.textCheckPoint("Received = 0", 1)
    Linksys_WMP300N.close()
    
def basicWirelessSettings_NOnly():
    wirelessRouter0.select()
    wirelessRouter0.gui.tabs.wireless()
    wirelessRouter0.gui.wireless.basicWirelessSettings.networkMode("Wireless-N Only")
    wirelessRouter0.gui.wireless.basicWirelessSettings.radioBand("Wide - 40MHz Channel")
    wirelessRouter0.gui.wireless.basicWirelessSettings.standardChannel("5 - 2\\.432GHz")
    wirelessRouter0.gui.wireless.basicWirelessSettings.saveSettingsButton()
    wirelessRouter0.close()
    
    Linksys_WMP300N.select()
    Linksys_WMP300N.desktop.applications.pcWireless()
    Linksys_WMP300N.desktop.pcWireless.tabs.connect()
    Linksys_WMP300N.desktop.pcWireless.connect.refreshButton()
    snooze(5)
    Linksys_WMP300N.desktop.pcWireless.connect.check.siteNetworkType("Wireless-N")
    Linksys_WMP300N.desktop.pcWireless.connect.check.siteRadioBand("40MHz")
    util.fastForwardTime()
    snooze(5)
    test.compare(findObject(Linksys_WMP300N.squishName + DesktopConst.pcwireless.connectTab.NETWORK_TABLE).rowCount, 1)
    Linksys_WMP300N.desktop.applications.commandPrompt()
    Linksys_WMP300N.desktop.commandPrompt.setText("ping 192.168.0.1")
    util.speedUpConvergence()
    Linksys_WMP300N.desktop.commandPrompt.textCheckPoint("Received = 0", 1)
    Linksys_WMP300N.close()

    PC_BG.select()
    PC_BG.desktop.applications.commandPrompt()
    PC_BG.desktop.commandPrompt.setText("ping 192.168.0.1")
    util.speedUpConvergence()
    PC_BG.desktop.commandPrompt.textCheckPoint("Received = 0", 1)
    PC_BG.close()

    Tablet_PC2.select()
    Tablet_PC2.desktop.applications.commandPrompt()
    Tablet_PC2.desktop.commandPrompt.setText("ping 192.168.0.1")
    util.speedUpConvergence()
    Tablet_PC2.desktop.commandPrompt.textCheckPoint("Received = 0", 1)
    Tablet_PC2.close()
    
    Pda1.select()
    Pda1.desktop.applications.commandPrompt()
    Pda1.desktop.commandPrompt.setText("ping 192.168.0.1")
    util.speedUpConvergence()
    Pda1.desktop.commandPrompt.textCheckPoint("Received = 0", 1)
    Pda1.close()

def disableSSIDBroadcast():
    wirelessRouter0.select()
    wirelessRouter0.gui.tabs.wireless()
    wirelessRouter0.gui.wireless.basicWirelessSettings.ssidBroadcastDisabled()
    wirelessRouter0.gui.wireless.basicWirelessSettings.saveSettingsButton()
    wirelessRouter0.close()
    
    Linksys_WMP300N.select()
    Linksys_WMP300N.desktop.applications.pcWireless()
    Linksys_WMP300N.desktop.pcWireless.tabs.connect()
    Linksys_WMP300N.desktop.pcWireless.connect.refreshButton()
    snooze(5)
    util.fastForwardTime()
    test.compare(findObject(Linksys_WMP300N.squishName + DesktopConst.pcwireless.connectTab.NETWORK_TABLE).rowCount, 0)
    Linksys_WMP300N.desktop.applications.commandPrompt()
    Linksys_WMP300N.desktop.commandPrompt.setText("ping 192.168.0.1")
    util.speedUpConvergence()
    Linksys_WMP300N.desktop.commandPrompt.textCheckPoint("Received = 0", 1)
    Linksys_WMP300N.close()
    
    wirelessRouter0.select()
    wirelessRouter0.gui.tabs.wireless()
    wirelessRouter0.gui.wireless.basicWirelessSettings.ssidBroadcastEnabled()
    wirelessRouter0.gui.wireless.basicWirelessSettings.saveSettingsButton()
    wirelessRouter0.close()
    
    Linksys_WMP300N.select()
    Linksys_WMP300N.desktop.applications.pcWireless()
    Linksys_WMP300N.desktop.pcWireless.tabs.connect()
    Linksys_WMP300N.desktop.pcWireless.connect.refreshButton()
    snooze(5)
    test.compare(findObject(Linksys_WMP300N.squishName + DesktopConst.pcwireless.connectTab.NETWORK_TABLE).rowCount, 1)
    Linksys_WMP300N.desktop.applications.commandPrompt()
    Linksys_WMP300N.desktop.commandPrompt.setText("ping 192.168.0.1")
    util.speedUpConvergence()
    Linksys_WMP300N.desktop.commandPrompt.textCheckPoint("Received = 0", 1)
