#**************************************************************************
#@author: Chris Allen
#@summary: EnvironmentConst contains the common constants used in the Environment Manager
#**************************************************************************
class EnvironmentConst:
    BASE = ':Environment'
    MAIN_WINDOW = ':Environment.DOCUMENT.HTML1'
    
    MEASURE_IMPERIAL = BASE + '.DOCUMENT.HTML1.BODY1.DIV2.INPUT2'
    MEASURE_METRIC = BASE + '.DOCUMENT.HTML1.BODY1.DIV2.INPUT3'

    SYNC_WITH_PHYSICAL =BASE + '.DOCUMENT.HTML1.BODY1.DIV1.INPUT1'
    LOCATIONS_BASE =    BASE + '.DOCUMENT.HTML1.BODY1.DIV1.DIV1'
    INTERCITY_LINK =    BASE + '.DOCUMENT.HTML1.BODY1.DIV1.DIV1.A1'
    HOME_CITY_LINK =    BASE + '.DOCUMENT.HTML1.BODY1.DIV1.DIV1.A2'
    CORPORATE_OFFICE =  BASE + '.DOCUMENT.HTML1.BODY1.DIV1.DIV1.A3'
    MAIN_WIRING_CLOSET =BASE + '.DOCUMENT.HTML1.BODY1.DIV1.DIV1.A4'
    
    TIME_MINUS_BUTTON = BASE + '.DOCUMENT.HTML1.BODY1.DIV2.BUTTON1'
    TIME_PLUS_BUTTON =  BASE + '.DOCUMENT.HTML1.BODY1.DIV2.BUTTON2'
    CURRENT_TIME =      BASE + '.DOCUMENT.HTML1.BODY1.DIV2.SPAN1'
    
    TIME_SCALE_EDIT =   BASE + '.DOCUMENT.HTML1.BODY1.DIV2.INPUT1'
    TIME_SCALE_SET =    BASE + '.DOCUMENT.HTML1.BODY1.DIV2.BUTTON3'
    
    MODE_PRESET =       BASE + '.DOCUMENT.HTML1.BODY1.DIV2.INPUT2'
    MODE_MANUAL =       BASE + '.DOCUMENT.HTML1.BODY1.DIV2.INPUT3'
    MODE_KEY_FRAMES =   BASE + '.DOCUMENT.HTML1.BODY1.DIV2.INPUT4'
    
    ENVIRONMENTAL_FACTORS_BASE = BASE + '.DOCUMENT.HTML1.BODY1.DIV2.DIV1'
    
    DAYLIGHT_VALUE =    BASE + '.DOCUMENT.HTML1.BODY1.DIV2.DIV1.DIV1.SPAN1'
    
    TEMP_EDIT =         BASE + '.DOCUMENT.HTML1.BODY1.DIV2.DIV1.DIV2.INPUT1'
    TEMP_SET_BUTTON =   BASE + '.DOCUMENT.HTML1.BODY1.DIV2.DIV1.DIV2.BUTTON1'
    TEMP_KEY_IMG =      BASE + '.DOCUMENT.HTML1.BODY1.DIV2.DIV1.DIV2.SPAN1.IMG1'
    TEMP_KEY_MINUS_BUTTON = BASE + '.DOCUMENT.HTML1.BODY1.DIV2.DIV1.DIV2.SPAN1.BUTTON1'
    TEMP_KEY_PLUS_BUTTON =  BASE + '.DOCUMENT.HTML1.BODY1.DIV2.DIV1.DIV2.SPAN1.BUTTON2'
    
    WIND_EDIT =         BASE + '.DOCUMENT.HTML1.BODY1.DIV2.DIV1.DIV3.INPUT1'
    WIND_SET_BUTTON =   BASE + '.DOCUMENT.HTML1.BODY1.DIV2.DIV1.DIV3.BUTTON1'
    WIND_KEY_IMG =      BASE + '.DOCUMENT.HTML1.BODY1.DIV2.DIV1.DIV3.SPAN1.IMG1'
    WIND_KEY_MINUS_BUTTON = BASE + '.DOCUMENT.HTML1.BODY1.DIV2.DIV1.DIV3.SPAN1.BUTTON1'
    WIND_KEY_PLUS_BUTTON =  BASE + '.DOCUMENT.HTML1.BODY1.DIV2.DIV1.DIV3.SPAN1.BUTTON2'
    
    HUMIDITY_EDIT =     BASE + '.DOCUMENT.HTML1.BODY1.DIV2.DIV1.DIV4.INPUT1'
    HUMIDITY_SET_BUTTON =   BASE + '.DOCUMENT.HTML1.BODY1.DIV2.DIV1.DIV4.BUTTON1'
    HUMIDITY_KEY_IMG =  BASE + '.DOCUMENT.HTML1.BODY1.DIV2.DIV1.DIV4.SPAN1.IMG1'
    HUMIDITY_KEY_MINUS_BUTTON = BASE + '.DOCUMENT.HTML1.BODY1.DIV2.DIV1.DIV4.SPAN1.BUTTON1'
    HUMIDITY_KEY_PLUS_BUTTON =  BASE + '.DOCUMENT.HTML1.BODY1.DIV2.DIV1.DIV4.SPAN1.BUTTON2'
    
    RAIN_EDIT =         BASE + '.DOCUMENT.HTML1.BODY1.DIV2.DIV1.DIV5.INPUT1'
    RAIN_SET_BUTTON =   BASE + '.DOCUMENT.HTML1.BODY1.DIV2.DIV1.DIV5.BUTTON1'
    RAIN_KEY_IMG =      BASE + '.DOCUMENT.HTML1.BODY1.DIV2.DIV1.DIV5.SPAN1.IMG1'
    RAIN_KEY_MINUS_BUTTON = BASE + '.DOCUMENT.HTML1.BODY1.DIV2.DIV1.DIV5.SPAN1.BUTTON1'
    RAIN_KEY_PLUS_BUTTON =  BASE + '.DOCUMENT.HTML1.BODY1.DIV2.DIV1.DIV5.SPAN1.BUTTON2'
    
    WATER_LEVEL_EDIT =  BASE + '.DOCUMENT.HTML1.BODY1.DIV2.DIV1.DIV6.INPUT1'
    WATER_LEVEL_SET_BUTTON =BASE + '.DOCUMENT.HTML1.BODY1.DIV2.DIV1.DIV6.BUTTON1'
    WATER_LEVEL_KEY_IMG =   BASE + '.DOCUMENT.HTML1.BODY1.DIV2.DIV1.DIV6.SPAN1.IMG1'
    WATER_LEVEL_KEY_MINUS_BUTTON =  BASE + '.DOCUMENT.HTML1.BODY1.DIV2.DIV1.DIV6.SPAN1.BUTTON1'
    WATER_LEVEL_KEY_PLUS_BUTTON =   BASE + '.DOCUMENT.HTML1.BODY1.DIV2.DIV1.DIV6.SPAN1.BUTTON2'
