class LoadNetworkConst:
    OPEN_BUTTON = ':btnOpen_HTML_Object'
    CANCEL_BUTTON = ':btnCancel_HTML_Object'
    SAVE_BUTTON = ':btnSave_HTML_Object'
    FILE_LOCATION = ':fileCategorySelect_HTML_Object'
    FILE_LOCATION_LOCAL = ':Local_HTML_Object'
    FILE_LOCATION_SAVE = ':Saves_HTML_Object'
    FILE_LOCATION_NETSPACE = ':Netspace_HTML_Object'
    FILE_LOCATION_DROPBOX = ':Dropbox_HTML_Object' 
    FILE_LOCATION_BOX = ':Box_HTML_Object'
    SAVE_FILE_LOCATION = ':locationSelect_HTML_Object'
    SAVE_FILE_EXTENSION = ':fileExtensionSelect_HTML_Object'
    SEARCH_FILE = ':fileSearchTextField_HTML_Object'
    SAVE_FILE_NAME = ':fldFileName_HTML_Object'
    OPEN_FILE_LIST = ':lstFiles_HTML_Object'
    PKA_ALERT_OK = ':alertOkBtn_HTML_Object'
    DONE_BUTTON = ':Done_HTML_Object'
    
    SAVE_OVERWRITE_YES = ':save_overwrite_HTML_Object'