#*******************************************************************************
#@author: Tuan Hoang
#@summary: TestActivityConst contains the common constants used in Test Activity
#*******************************************************************************
class TestActivityConst:
    ACTIVITY_RESULTS_OVERALL_FEEDBACK_TAB = ":CAppWindowBase.CBaseCheckAnswerPage.m_resultsTab.qt_tabwidget_tabbar.TabItem1"
    ACTIVITY_RESULTS_ASSESSMENT_ITEMS_TAB = ":CAppWindowBase.CBaseCheckAnswerPage.m_resultsTab.qt_tabwidget_tabbar.TabItem2"
    ACTIVITY_RESULTS_CONNECTIVITY_TESTS_TAB = ":CAppWindowBase.CBaseCheckAnswerPage.m_resultsTab.qt_tabwidget_tabbar.TabItem3"
    TEST_ACTIVITY = ":Activity_Wizard.m_navigationBtnGrpBox.TestActivityBtn"
    ACTIVITY_WIZARD_ICON = ":CAppWindowBase.Activity Wizard Icon"
    EXIT_TEST_MODE_DIALOG = ":CAppWindowBase.Exit Test Mode? -- Packet Tracer"
    EXIT_TEST_MODE_YES = ":CAppWindowBase.Exit Test Mode? -- Packet Tracer.qt_msgbox_buttonbox.Yes"
    EXIT_TEST_MODE_NO = ":CAppWindowBase.Exit Test Mode? -- Packet Tracer.qt_msgbox_buttonbox.No"
    INSTRUCTIONS_WINDOW = ":CBaseInstructionDialog."
    TIME_LEFT = ":CBaseInstructionDialog.m_timeLbl"
    TOP = ":CBaseInstructionDialog.topCB"
    CHECK_RESULTS = ":CBaseInstructionDialog.checkAnswerBtn"
    ACTIVITY_RESULTS_DIALOG = ":CAppWindowBase.CBaseCheckAnswerPage"
    ACTIVITY_RESULTS_TABBAR = ":CAppWindowBase.CBaseCheckAnswerPage.m_resultsTab.qt_tabwidget_tabbar"
    ACTIVITY_RESULTS_OVERALL_FEEDBACK = "Overall Feedback"
    ACTIVITY_RESULTS_OVERALL_FEEDBACK_LABEL = ":CAppWindowBase.CBaseCheckAnswerPage.m_resultsTab.qt_tabwidget_stackedwidget.m_overallFeedbackTab.m_feedbackLbl"
    ACTIVITY_RESULTS_OVERALL_FEEDBACK_TEXT = ":CAppWindowBase.CBaseCheckAnswerPage.m_resultsTab.qt_tabwidget_stackedwidget.m_overallFeedbackTab.QWebView1.DOCUMENT.HTML1.BODY1"
    ACTIVITY_RESULTS_OVERALL_FEEDBACK_WEBVIEW = ":CAppWindowBase.CBaseCheckAnswerPage.m_resultsTab.qt_tabwidget_stackedwidget.m_overallFeedbackTab.QWebView1"
    ACTIVITY_RESULTS_ASSESSMENT_ITEMS = "Assessment Items"
    ACTIVITY_RESULTS_ASSESSMENT_ITEMS_SCORE_LABEL = ":CAppWindowBase.CBaseCheckAnswerPage.m_resultsTab.qt_tabwidget_stackedwidget.m_assessmentItemsTab.pointsLbl" 
    ACTIVITY_RESULTS_ASSESSMENT_ITEMS_SCORE = ":CAppWindowBase.CBaseCheckAnswerPage.m_resultsTab.qt_tabwidget_stackedwidget.m_assessmentItemsTab.m_pointsText"
    ACTIVITY_RESULTS_ASSESSMENT_ITEMS_ITEM_COUNT_LABEL = ":CAppWindowBase.CBaseCheckAnswerPage.m_resultsTab.qt_tabwidget_stackedwidget.m_assessmentItemsTab.textLabel1_8"
    ACTIVITY_RESULTS_ASSESSMENT_ITEMS_ITEM_COUNT = ":CAppWindowBase.CBaseCheckAnswerPage.m_resultsTab.qt_tabwidget_stackedwidget.m_assessmentItemsTab.m_compCompText"
    ACTIVITY_RESULTS_ASSESSMENT_ITEMS_COMPONENT_LABEL = ":CAppWindowBase.CBaseCheckAnswerPage.m_resultsTab.qt_tabwidget_stackedwidget.m_assessmentItemsTab.m_compPointLbl"
    ACTIVITY_RESULTS_CONNECTIVITY_TESTS = "Connectivity Tests"
    ACTIVITY_RESULTS_CONNECTIVITY_TESTS_FEEDBACK_LABEL = ":CAppWindowBase.CBaseCheckAnswerPage.m_resultsTab.qt_tabwidget_stackedwidget.m_connectivityTestsTab.m_feedbackLbl_2"
    ACTIVITY_RESULTS_CONNECTIVITY_VIEWPORT = ":CAppWindowBase.CBaseCheckAnswerPage.m_resultsTab.qt_tabwidget_stackedwidget.m_connectivityTestsTab.m_PDUTable.qt_viewport"
    ACTIVITY_RESULTS_CONNECTIVITY_TABLE = ":CAppWindowBase.CBaseCheckAnswerPage.m_resultsTab.qt_tabwidget_stackedwidget.m_connectivityTestsTab.m_PDUTable"
    ACTIVITY_RESULTS_CLOSE = ":CAppWindowBase.CBaseCheckAnswerPage.m_closeButton"
    ASSESSMENT_ITEMS_TREE = ":CAppWindowBase.CBaseCheckAnswerPage.m_resultsTab.qt_tabwidget_stackedwidget.m_assessmentItemsTab.m_checkAnswerTree"
    RESET_ACTIVITY = ":CBaseInstructionDialog.resetBtn"
    RESET_ACTIVITY_DIALOG = ":CBaseInstructionDialog.Reset Activity? -- Packet Tracer"
    RESET_ACTIVITY_DIALOG_OK = ":CBaseInstructionDialog.Reset Activity? -- Packet Tracer.qt_msgbox_buttonbox.Ok"
    RESET_ACTIVITY_DIALOG_CANCEL = ":CBaseInstructionDialog.Reset Activity? -- Packet Tracer.qt_msgbox_buttonbox.Cancel"
    NEXT_PAGE = ":CBaseInstructionDialog.nextBtn"
    PREVIOUS_PAGE = ":CBaseInstructionDialog.prevBtn"
    INSTRUCTION_BOX = ":CBaseInstructionDialog"
    INSTRUCTION_BOX_TEXT = ":CBaseInstructionDialog.CWebView1"
    INSTRUCTION_BOX_TEXT_SCRIPT = ":CBaseInstructionDialog.CWebView1.DOCUMENT.HTML1.BODY1.PRE1"
    INSTRUCTION_BOX_TEXT_MENU = ":CBaseInstructionDialog.CWebView1.QMenu1"
    INSTRUCTION_BOX_TIME_LABEL = ":CBaseInstructionDialog.m_timeLbl"
    INSTRUCTION_BOX_PROGRESS_LABEL = ":CBaseInstructionDialog.progressLbl"
    INSTRUCTION_BOX_TOP = ":CBaseInstructionDialog.topCB"
    INSTRUCTION_BOX_PAGE_NUM = ":CBaseInstructionDialog.m_pageNum"
    INSTRUCTION_BOX_VSCROLLBAR = ":CBaseInstructionDialog.m_txtInfo.qt_vbar"
    INSTRUCTION_BOX_TEXT_CONTENT = ":CBaseInstructionDialog.CWebView1.DOCUMENT.HTML1"
    RESTART_ACTIVITY_DIALOG = ":CAppWindowBase.CBaseCheckAnswerPage.Restart Activity? -- Packet Tracer"
    RESTART_ACTIVITY_DIALOG_YES = ":CAppWindowBase.CBaseCheckAnswerPage.Restart Activity? -- Packet Tracer.qt_msgbox_buttonbox.Yes"
    RESTART_ACTIVITY_DIALOG_NO = ":CAppWindowBase.CBaseCheckAnswerPage.Restart Activity? -- Packet Tracer.qt_msgbox_buttonbox.No"
    ASSESSMENT_ITEMS_VBAR = ":CAppWindowBase.CBaseCheckAnswerPage.m_resultsTab.qt_tabwidget_stackedwidget.m_assessmentItemsTab.m_checkAnswerTree.qt_scrollarea_vcontainer.QScrollBar1"
    ASSESSMENT_ITEMS_HBAR = ":CAppWindowBase.CBaseCheckAnswerPage.m_resultsTab.qt_tabwidget_stackedwidget.m_assessmentItemsTab.m_checkAnswerTree.qt_scrollarea_hcontainer.QScrollBar1"