class AddPduConst:
	CREATE_PDU_BUTTON = ':send_button_HTML_Object'
	SOURCE_DEVICE = ':sourceDevice_text_HTML_Object'
	AUTO_SELECT_PORT = ':autoSelectPort_checkbox_HTML_Object'
	OUTGOING_PORT_SELECT = ':outgoingPort_select_HTML_Object'
	SELECT_APPLICATION = ':application_select_HTML_Object'
	DESTINATION_IP_ADDRESS = ':destinationIP_text_HTML_Object'
	SOURCE_IP_ADDRESS = ':sourceIP_text_HTML_Object'
	TOS = ':tos_numField_HTML_Object'
	TTL = ':ttl_numField_HTML_Object'
	SEQUENCE_NUMBER = ':sequence_numField_HTML_Object'
	SOURCE_PORT = ':startingSourcePort_text_HTML_Object'
	DESTINATION_PORT = ':destinationPort_text_HTML_Object'
	SIZE = ':size_numField_HTML_Object'
	ONE_SHOT_TIME_RADIO = ':oneShot_radio_HTML_Object'
	PERIODIC_RADIO = ':periodic_radio_HTML_Object'
	SECONDS_ONE_SHOT = ':oneShot_textField_HTML_Object'
	SECONDS_PERIODIC = ':periodic_textField_HTML_Object'
	pass