#***********************************************************************************
#@author: Tuan Hoang
#@summary: InitialNetworkConst contains the common constants used in Initial Network
#***********************************************************************************
class InitialNetworkConst:
    INITIAL_NETWORK = ":Activity_Wizard.m_navigationBtnGrpBox.InitialNetworkBtn"
    TAB_BAR = ":Activity_Wizard.m_contents.Initial_Network.m_initNetTabs.qt_tabwidget_tabbar"
    SHOW_INITIAL_NETWORK = ":Activity_Wizard.m_contents.Initial_Network.groupBox_21.ShowInitNetworkBtn"
    ACTIVITY_WIZARD_ICON = ":CAppWindowBase.Activity Wizard Icon"
    COPY_FROM_ANSWER_NETWORK = ":Activity_Wizard.m_contents.Initial_Network.groupBox_21.CopyAnsNetBtn"
    COPY_FROM_ANSWER_NETWORK_DIALOG = ":Activity_Wizard.Replace Initial Network? -- Packet Tracer"
    COPY_FROM_ANSWER_NETWORK_DIALOG_YES = ":Activity_Wizard.Replace Initial Network? -- Packet Tracer.qt_msgbox_buttonbox.Yes"
    COPY_FROM_ANSWER_NETWORK_DIALOG_NO = ":Activity_Wizard.Replace Initial Network? -- Packet Tracer.qt_msgbox_buttonbox.Nov"
    IMPORT_FILE_TO_INITIAL_NETWORK = ":Activity_Wizard.m_contents.Initial_Network.groupBox_22.ImportInitNetworkBtn"
    IMPORT_FILE_TO_INITIAL_NETWORK_DIALOG = ":Activity_Wizard.QFileDialog.fileNameEdit"
    IMPORT_FILE_TO_INITIAL_NETWORK_DIALOG_OK = ":Activity_Wizard.QFileDialog.buttonBox.Open"
    IMPORT_FILE_TO_INITIAL_NETWORK_DIALOG_CANCEL = ":Activity_Wizard.QFileDialog.buttonBox.Cancel"
    EXPORT_INITIAL_NETWORK_TO_FILE = ":Activity_Wizard.m_contents.Initial_Network.groupBox_22.ExportInitNetworkBtn"
    EXPORT_INITIAL_NETWORK_TO_FILE_DIALOG = ":Activity_Wizard.QFileDialog.fileNameEdit"
    EXPORT_INITIAL_NETWORK_TO_FILE_DIALOG_OK = ":Activity_Wizard.QFileDialog.buttonBox.Save"
    EXPORT_INITIAL_NETWORK_TO_FILE_DIALOG_CANCEL = ":Activity_Wizard.QFileDialog.buttonBox.Cancel"
    
    #EXPORT_OVERWRITE_FILE_DIALOG = ":Activity_Wizard.QFileDialog.Export File"
    EXPORT_OVERWRITE_FILE_DIALOG = ":Overwrite File?"
    #EXPORT_OVERWRITE_FILE_DIALOG_YES = ":Activity_Wizard.QFileDialog.Export File.qt_msgbox_buttonbox.Yes"
    EXPORT_OVERWRITE_FILE_DIALOG_YES = ":Overwrite File?.qt_msgbox_buttonbox.Yes"
    #EXPORT_OVERWRITE_FILE_DIALOG_NO = ":Activity_Wizard.QFileDialog.Export File.qt_msgbox_buttonbox.No"
    EXPORT_OVERWRITE_FILE_DIALOG_NO = ":Overwrite File?.qt_msgbox_buttonbox.No"    
    EXPORT_OVERWRITE_FILE_DIALOG_LABEL = ":Activity_Wizard.QFileDialog.Export File.qt_msgbox_label"
    
    LOCKING_OPTIONS_EXPAND_COLLAPSE_ALL_BUTTON = ':Activity_Wizard.m_contents.Initial_Network.m_initNetTabs.qt_tabwidget_stackedwidget.m_lockingTab.m_btnExpCollapseAllInit'
    
    LOCKING_ITEMS_TREE = ":Activity_Wizard.m_contents.Initial_Network.m_initNetTabs.qt_tabwidget_stackedwidget.m_lockingTab.CLockingTree1"
    SWITCH_TO_LOGICAL_WORKSPACE = ":Activity_Wizard.m_contents.Initial_Network.m_initNetTabs.qt_tabwidget_stackedwidget.m_lockingTab.CLockingTree1.item_0/0.item_0/0.item_0/0"
    SWITCH_TO_PHYSICAL_WORKSPACE = ":Activity_Wizard.m_contents.Initial_Network.m_initNetTabs.qt_tabwidget_stackedwidget.m_lockingTab.CLockingTree1.item_0/0.item_0/0.item_1/0"
    SWITCH_TO_REALTIME_MODE = ":Activity_Wizard.m_contents.Initial_Network.m_initNetTabs.qt_tabwidget_stackedwidget.m_lockingTab.CLockingTree1.item_0/0.item_0/0.item_2/0"
    SWITCH_TO_SIMULATION_MODE = ":Activity_Wizard.m_contents.Initial_Network.m_initNetTabs.qt_tabwidget_stackedwidget.m_lockingTab.CLockingTree1.item_0/0.item_0/0.item_3/0"
    SAVE_ACTIVITY = ":Activity_Wizard.m_contents.Initial_Network.m_initNetTabs.qt_tabwidget_stackedwidget.m_lockingTab.CLockingTree1.item_0/0.item_0/0.item_4/0"
    PRINT_ACTIVITY = ":Activity_Wizard.m_contents.Initial_Network.m_initNetTabs.qt_tabwidget_stackedwidget.m_lockingTab.CLockingTree1.item_0/0.item_0/0.item_5/0"
    COPY_AND_PASTE = ":Activity_Wizard.m_contents.Initial_Network.m_initNetTabs.qt_tabwidget_stackedwidget.m_lockingTab.CLockingTree1.item_0/0.item_0/0.item_6/0"
    VIEW_COMMAND_LOG = ":Activity_Wizard.m_contents.Initial_Network.m_initNetTabs.qt_tabwidget_stackedwidget.m_lockingTab.CLockingTree1.item_0/0.item_0/0.item_7/0"
    HAND_TOOL = ":Activity_Wizard.m_contents.Initial_Network.m_initNetTabs.qt_tabwidget_stackedwidget.m_lockingTab.CLockingTree1.item_0/0.item_0/0.item_8/0"
    NOTE_TOOL = ":Activity_Wizard.m_contents.Initial_Network.m_initNetTabs.qt_tabwidget_stackedwidget.m_lockingTab.CLockingTree1.item_0/0.item_0/0.item_9/0"
    DELETE_TOOL = ":Activity_Wizard.m_contents.Initial_Network.m_initNetTabs.qt_tabwidget_stackedwidget.m_lockingTab.CLockingTree1.item_0/0.item_0/0.item_10/0"
    INSPECTION_TOOL = ":Activity_Wizard.m_contents.Initial_Network.m_initNetTabs.qt_tabwidget_stackedwidget.m_lockingTab.CLockingTree1.item_0/0.item_0/0.item_11/0"
    DRAWING_TOOL = ":Activity_Wizard.m_contents.Initial_Network.m_initNetTabs.qt_tabwidget_stackedwidget.m_lockingTab.CLockingTree1.item_0/0.item_0/0.item_12/0"
    RESIZE_TOOL = ":Activity_Wizard.m_contents.Initial_Network.m_initNetTabs.qt_tabwidget_stackedwidget.m_lockingTab.CLockingTree1.item_0/0.item_0/0.item_13/0"
    LOCK_MAIN = ":Activity_Wizard.m_contents.Initial_Network.m_initNetTabs.qt_tabwidget_stackedwidget.m_lockingTab.CLockingTree1.item_0/0.item_0/0.item_14/0"
    LOCK_RIGHT = ":Activity_Wizard.m_contents.Initial_Network.m_initNetTabs.qt_tabwidget_stackedwidget.m_lockingTab.CLockingTree1.item_0/0.item_0/0.item_15/0"
    LOCK_BOTTOM = ":Activity_Wizard.m_contents.Initial_Network.m_initNetTabs.qt_tabwidget_stackedwidget.m_lockingTab.CLockingTree1.item_0/0.item_0/0.item_16/0"
    PREFERENCES = ":Activity_Wizard.m_contents.Initial_Network.m_initNetTabs.qt_tabwidget_stackedwidget.m_lockingTab.CLockingTree1.item_0/0.item_0/0.item_17/0"
    ACTIVITY = ":Activity_Wizard.m_contents.Initial_Network.m_initNetTabs.qt_tabwidget_stackedwidget.m_lockingTab.CLockingTree1.item_0/0.item_0/0.item_18/0"
    SCROLLBAR = ":Activity_Wizard.m_contents.Initial_Network.m_initNetTabs.qt_tabwidget_stackedwidget.m_lockingTab.CLockingTree1.qt_scrollarea_vcontainer.QScrollBar1"

    EXPORT_INITIAL_NETWORK_REPLACE_BOX = ":Activity_Wizard.QFileDialog.Export File"
    EXPORT_INITIAL_NETWORK_REPLACE_BOX_YES = ":Activity_Wizard.QFileDialog.Export File.qt_msgbox_buttonbox.Yes"
    EXPORT_INITIAL_NETWORK_REPLACE_BOX_NO = ":Activity_Wizard.QFileDialog.Export File.qt_msgbox_buttonbox.No"
    
    LOCKING_OPTIONS_SETUP_TAB = "Locking Options"
    INITIAL_NETWORK_SETUP_TAB = "Initial Network Setup"
    INITIAL_NETWORK_SETUP_TREE = ":Activity_Wizard.m_contents.Initial_Network.m_initNetTabs.qt_tabwidget_stackedwidget.initSetupTab.splitter_5.m_initialTreeLV"
    INITIAL_NETWORK_SETUP_TREE_EDIT = ":Activity_Wizard.m_contents.Initial_Network.m_initNetTabs.qt_tabwidget_stackedwidget.initSetupTab.splitter_5.m_initialTreeLV.qt_scrollarea_viewport.QExpandingLineEdit1"
    
    LOCKING_TREE_EXPLANATION_TEXT = ":Activity_Wizard.m_contents.Initial_Network.m_initNetTabs.qt_tabwidget_stackedwidget.m_lockingTab.textLabel3"
    
    OBJECT_LOCATIONS = "Object Locations"
    OVERWRITE_SELECTED_LOCATION = ":Activity_Wizard.m_contents.Initial_Network.m_initNetTabs.qt_tabwidget_stackedwidget.objLocTab.m_btnOverwriteLoc"
    APPEND_CURRENT_LOCATIONS = ":Activity_Wizard.m_contents.Initial_Network.m_initNetTabs.qt_tabwidget_stackedwidget.objLocTab.m_btnAppendLoc"
    LOAD_LOCATIONS = ":Activity_Wizard.m_contents.Initial_Network.m_initNetTabs.qt_tabwidget_stackedwidget.objLocTab.m_btnLoadLoc"
    DELETE_SELECTED_LOCATIONS = ":Activity_Wizard.m_contents.Initial_Network.m_initNetTabs.qt_tabwidget_stackedwidget.objLocTab.m_btnDeleteLoc"
    INDEX_VARIABLE = ':Activity_Wizard.m_contents.Initial_Network.m_initNetTabs.qt_tabwidget_stackedwidget.objLocTab.m_txtLoadIndex'
    OBJECT_LOCATIONS_TABLE = ':Activity_Wizard.m_contents.Initial_Network.m_initNetTabs.qt_tabwidget_stackedwidget.objLocTab.m_locTbl'
    
    EDIT_SET = ":Activity_Wizard.m_contents.Initial_Network.m_initNetTabs.qt_tabwidget_stackedwidget.objLocTab.m_txtEditSet"
    LOCK_TABLE = ":Activity_Wizard.m_contents.Initial_Network.m_initNetTabs.qt_tabwidget_stackedwidget.objLocTab.m_locTbl"
    
    class LockingItems:
        LT_LOCKING = "Locking"
        INTERFACE = "Locking.Interface"
        TOPOLOGY = "Locking.Topology"
        SIMULATION = "Locking.Simulation"
        class Interface:
            SWITCHING_LOGICAL_WORKSPACE = "Locking.Interface.Switching to Logical Workspace"
            SWITCHING_PHYSICAL_WORKSPACE = "Locking.Interface.Switching to Physical Workspace"
            SWITCHING_REALTIME_MODE = "Locking.Interface.Switching to Realtime Mode"
            SWITCHING_SIMULATION_MODE = "Locking.Interface.Switching to Simulation Mode"
            SAVE_ACTIVITY = "Locking.Interface.Save Activity"
            PRINT_ACTIVITY = "Locking.Interface.Print Activity"
            COPY_PASTE = "Locking.Interface.Copy and Paste"
            VIEW_COMMAND_LOG = "Locking.Interface.View Command Log"
            HAND_TOOL = "Locking.Interface.Hand Tool"
            NOTE_TOOL = "Locking.Interface.Note Tool"
            DELETE_TOOL = "Locking.Interface.Delete Tool"
            INSPECT_TOOL = "Locking.Interface.Inspection Tool"
            DRAW_TOOL = "Locking.Interface.Drawing Tool"
            RESIZE_TOOL = "Locking.Interface.Resize Tool"
            LOCK_MAIN_TOOLBAR = "Locking.Interface.Lock Main Toolbar Toggle"
            LOCK_RIGHT_TOOLBAR = "Locking.Interface.Lock Right Toolbar Toggle"
            LOCK_BOTTOM_TOOLBAR = "Locking.Interface.Lock Bottom Toolbar Toggle"
            PREFERENCES = "Locking.Interface.Preferences (Depricated)"
            class Preferences:
                ANIMATION = "Locking.Interface.Preferences.Toggling Animation (Deprecated)"
                AUTO_DOCK = "Locking.Interface.Preferences.Toggling Auto Dock Popup Window (Deprecated)"
                SOUND  = "Locking.Interface.Preferences.Toggling Sound (Deprecated)"
                TELEPHONY = "Locking.Interface.Preferences.Toggling Telephony Sound (Deprecated)"
                SHOW_PORT_INFO = "Locking.Interface.Preferences.Toggling Show Port Information (Deprecated)"
                HIDE_LINK_LIGHTS = "Locking.Interface.Preferences.Hide Link Light (Deprecated)"
                ENABLE_CABLE_LENGTH = "Locking.Interface.Preferences.Enable Cable Length (Deprecated)"
                LOCK_INTERFACE_TAB = "Locking.Interface.Preferences.Lock Interface Tab (Deprecated)"
                LOCK_ADMINISTRATIVE_TAB = "Locking.Interface.Preferences.Lock Administrative Tab (Deprecated)"
                LOCK_HIDE_TAB = "Locking.Interface.Preferences.Lock Hide Tab (Deprecated)"
                LOCK_CUSTOM_INT_TAB = "Locking.Interface.Preferences.Lock Custom Interfaces Tab (Deprecated)"
                ACTIVITY = "Locking.Interface.Activity"
            class Activity:
                VIEW_ASSESMENT_ITEMS = "Locking.Interface.Activity.View Assessment Items"
                VIEW_CONNECTIVITY_TEST = "Locking.Interface.Activity.View Connectivity Tests"
                EDIT_INSTRUCTIONS = "Locking.Interface.Activity.Edit Instructions (Deprecated)"
                CHECK_RESULTS = "Locking.Interface.Activity.Check Results"
                RESET_ACTIVITY = "Locking.Interface.Activity.Reset Activty"
                FF_TIME = "Locking.Interface.Activity.Fast Forward Time"
        class Topology:
            GLOBAL = "Locking.Topology.Global"
            class Global:
                CREATE_DEVICE = "Locking.Topology.Global.Create Device"
                REMOVE_DEVICE = "Locking.Topology.Global.Remove Device"
                TOGGLE_POWER = "Locking.Topology.Global.Toggle Power"
                CONFIGURE_DEVICES = "Locking.Topology.Global.Configure Devices"
                MOVE_DEVICES = "Locking.Topology.Global.Move Devices"
                USE_CLI_TAB = "Locking.Topology.Global.Use CLI Tab"
                USE_DESKTOP_TAB = "Locking.Topology.Global.Use Desktop Tab"
                USE_CONFIG_TAB = "Locking.Topology.Global.Use Config Tab"
                CHANGE_INTERFACE = "Locking.Topology.Global.Change Interface"
                REMOVE_INTERFACE = "Locking.Topology.Global.Remove Interface"
                ENTER_CLUSTER = "Locking.Topology.Global.Enter Cluster"
                MOVE_CLUSTER = "Locking.Topology.Global.Move Cluster"
                CREATE_PHYSICAL_LEVEL = "Locking.Topology.Global.Create Physical Level"
                REMOVE_PHYSICAL_LEVEL = "Locking.Topology.Global.Remove Physical Level"
                CHANGE_PHYSICAL_LEVEL = "Locking.Topology.Global.Change Physical Level"
                GLOBAL_TOOLTIP = "Locking.Topology.Global.Global Tooltip"
                CHANGE_NOTES = "Locking.Topology.Global.Change Notes/Annotations"
                MOVE_NOTES = "Locking.Topology.Global.Move Notes/Annotations"
                REMOVE_NOTES = "Locking.Topology.Global.Remove Notes/Annotations"
                AUTO_CONNECT = "Locking.Topology.Global.Auto Connect"
                EXPORT_IMPORT_IOS = "Locking.Topology.Global.Export/Import IOS Config"
                CHANGE_DISPLAY_NAMES = "Locking.Topology.Global.Change Display Names"
                READ_ONLY_DESKTOP = "Locking.Topology.Global.Read Only Desktop Applets"
                LOCK_DESKTOP_APPLETS = "Locking.Topology.Global.Lock Desktop Applets"
            EXISTING_DEVICES = "Locking.Topology.Existing Devices"
            EXISTING_ANNOTATIONS = "Locking.Topology.Existing Annotations"
            CLUSTERS = "Locking.Topology.Clusters"
            REMOTE_NETS = "Locking.Topology.Remote Networks"
            class RemoteNetworks:
                PEER_0 = "Locking.Topology.Remote Networks.Peer0"
                CONNECTION_TYPE = ".Connection Type"
                PEER_ADDRESS = ".Peer Address"
                PEER_PORT = ".Peer Port Number"
                PEER_NET_NAME = ".Peer Network Name"
                PASSWORD = ".Password"
        class Simulation:
            GLOBAL = "Locking.Simulation.Global"
            class Global:
                CREATE_SCENARIO = "Locking.Simulation.Global.Create Scenarios"
                REMOVE_SCENARIO = "Locking.Simulation.Global.Remove Scenarios"
                RENAME_SCENARIO = "Locking.Simulation.Global.Rename Scenarios"
                CREATE_SIMPLE_PDU = "Locking.Simulation.Global.Create Simple PDU"
                CREATE_CUSTOM_PDU = "Locking.Simulation.Global.Create Custom PDU"
                REMOVE_PDU = "Locking.Simulation.Global.Remove PDU"
                EDIT_PDU = "Locking.Simulation.Global.Edit PDU"
                ALL_PDU_INFO = "Locking.Simulation.Global.All PDU info"
                class AllPDUInfo:
                    OPEN_ALL_PDU = "Locking.Simulation.Global.All PDU info.Open All PDU Info"
                    VIEW_OSI_MODEL_DETAIL = "Locking.Simulation.Global.All PDU info.View OSI Model Detail"
                    VIEW_INBOUND_DETAIL = "Locking.Simulation.Global.All PDU info.View Inbound Detail"
                    VIEW_OUTBOUND_DETAIL = "Locking.Simulation.Global.All PDU info.View Outbound Detail"
            EXISTING_SCENARIOS = "Locking.Simulation.Existing Scenarios"
            class ExistingScenarios:
                SCENARIO_0 = "Locking.Simulation.Existing Scenarios.Scenario 0"
                class Scenario_0:
                    REMOVE_SCENARIO = "Locking.Simulation.Existing Scenarios.Scenario 0.Remove Scenario"
                    RENAME_SCENARIO = "Locking.Simulation.Existing Scenarios.Scenario 0.Rename Scenario"
                    CREATE_SIMPLE_PDU = "Locking.Simulation.Existing Scenarios.Scenario 0.Create Simple PDU"
                    CREATE_CUSTOM_PDU = "Locking.Simulation.Existing Scenarios.Scenario 0.Create Custom PDU"
                    REMOVE_PDU = "Locking.Simulation.Existing Scenarios.Scenario 0.Remove PDU"
                    EDIT_PDU = "Locking.Simulation.Existing Scenarios.Scenario 0.Edit PDU"
                    PDU_INFO = "Locking.Simulation.Existing Scenarios.Scenario 0.PDU Info"
                    class PDUInfo:
                        OPEN_PDU_INFO = "Locking.Simulation.Existing Scenarios.Scenario 0.PDU Info.Open PDU Info"
                        VIEW_OSI_MODEL_DETAIL = "Locking.Simulation.Existing Scenarios.Scenario 0.PDU Info.View OSI Model Detail"
                        VIEW_INBOUND_DETAIL = "Locking.Simulation.Existing Scenarios.Scenario 0.PDU Info.View Inbound Detail"
                        VIEW_OUTBOUND_DETAIL = "Locking.Simulation.Existing Scenarios.Scenario 0.PDU Info.View Outbound Detail"
            
    
    class InitialNetworkSetup:
        EXPAND_COLLAPSE_ALL = ":Activity_Wizard.m_contents.Initial_Network.m_initNetTabs.qt_tabwidget_stackedwidget.initSetupTab.m_btnExpCollapseAllInitSetup"
        