#Thi
from API.ComponentBox import ComponentBoxConst
from API.Device.LinksysRouter.LinksysRouter import LinksysRouter
from API.Device.EndDevice.PC.PC import PC
from API.Utility.Util import Util
from API.Utility.Util import UtilConst
from API.Device.Router.Router import Router

#Function initialization
util = Util()

#Device initialization
Linksys_WMP300N = PC(ComponentBoxConst.DeviceModel.CUSTOM_WIRELESS_PC, 445, 115, "Linksys_WMP300N")
PC_BG = PC(ComponentBoxConst.DeviceModel.CUSTOM_WIRELESS_PC, 445, 214, "PC_BG")
PC_A = PC(ComponentBoxConst.DeviceModel.CUSTOM_WIRELESS_PC, 450, 312, "PC_A")
Tablet_PC2 = PC(ComponentBoxConst.DeviceModel.CUSTOM_WIRELESS_PC, 447, 42, "Tablet PC2")
Pda1 = PC(ComponentBoxConst.DeviceModel.CUSTOM_WIRELESS_PC, 147, 312, "Pda1")
wirelessRouter0 = LinksysRouter(ComponentBoxConst.DeviceModel.LINKSYS, 171, 144, "Wireless Router0")

def main():
    test.log("bug#4734, #4727, #4732")
    createTopology()
    preventAll()
    permitAll()
    permit_PC_BG()
    prevent_PC_BG()
    disable_Mac()

def createTopology():
    #a.    Create and connect devices according to diagram.
    #a.    On PC0, remove Ethernet interface and insert Linksys WRT-300N.
    util.open("UI53_Linksys.pkt", UtilConst.UI_TEST)
    
def preventAll():
    wirelessRouter0.select()
    wirelessRouter0.clickGuiTab()
    wirelessRouter0.gui.tabs.wireless()
    wirelessRouter0.gui.tabs.wirelessMacFilter()
    wirelessRouter0.gui.wireless.macFilter.addMac("00:90:0C:1B:C8:B5", 1)
    wirelessRouter0.gui.wireless.macFilter.addMac("00:06:2A:63:CC:AE", 2)
    wirelessRouter0.gui.wireless.macFilter.addMac("00:01:64:AC:32:18", 3)
    wirelessRouter0.gui.wireless.macFilter.addMac("00:E0:F7:20:82:8D", 4)
    wirelessRouter0.gui.wireless.macFilter.addMac("00:60:2F:E3:86:92", 5)
    wirelessRouter0.gui.wireless.macFilter.saveSettingsButton()
    wirelessRouter0.close()
    
    Linksys_WMP300N.select()
    Linksys_WMP300N.clickDesktopTab()
    Linksys_WMP300N.desktop.applications.commandPrompt()
    Linksys_WMP300N.desktop.commandPrompt.setText("ping 192.168.0.1")
    util.fastForwardTime()
    util.fastForwardTime()
    Linksys_WMP300N.desktop.commandPrompt.textCheckPoint("Received = 0", 1)
    Linksys_WMP300N.close()
    
    PC_BG.select()
    PC_BG.clickDesktopTab()
    PC_BG.desktop.applications.commandPrompt()
    PC_BG.desktop.commandPrompt.setText("ping 192.168.0.1")
    util.fastForwardTime()
    util.fastForwardTime()
    PC_BG.desktop.commandPrompt.textCheckPoint("Received = 0", 1)
    PC_BG.close()
    
    Tablet_PC2.select()
    Tablet_PC2.clickDesktopTab()
    Tablet_PC2.desktop.applications.commandPrompt()
    Tablet_PC2.desktop.commandPrompt.setText("ping 192.168.0.1")
    util.fastForwardTime()
    util.fastForwardTime()
    Tablet_PC2.desktop.commandPrompt.textCheckPoint("Received = 0", 1)
    Tablet_PC2.close()
    
    Pda1.select()
    Pda1.clickDesktopTab()
    Pda1.desktop.applications.commandPrompt()
    Pda1.desktop.commandPrompt.setText("ping 192.168.0.1")
    util.fastForwardTime()
    util.fastForwardTime()
    Pda1.desktop.commandPrompt.textCheckPoint("Received = 0", 1)
    Pda1.close()
    
def permitAll():
    wirelessRouter0.select()
    wirelessRouter0.gui.tabs.wireless()
    wirelessRouter0.gui.tabs.wirelessMacFilter()
    wirelessRouter0.gui.wireless.macFilter.permitPcsListed()
    wirelessRouter0.gui.wireless.macFilter.saveSettingsButton()
    wirelessRouter0.close()
    
    Linksys_WMP300N.select()
    Linksys_WMP300N.clickDesktopTab()
    Linksys_WMP300N.desktop.applications.commandPrompt()
    Linksys_WMP300N.desktop.commandPrompt.setText("ping 192.168.0.1")
    util.fastForwardTime()
    util.fastForwardTime()
    Linksys_WMP300N.desktop.commandPrompt.textCheckPoint("Received = 0", 1)
    Linksys_WMP300N.close()
    
    PC_BG.select()
    PC_BG.clickDesktopTab()
    PC_BG.desktop.applications.commandPrompt()
    PC_BG.desktop.commandPrompt.setText("ping 192.168.0.1")
    util.fastForwardTime()
    util.fastForwardTime()
    PC_BG.desktop.commandPrompt.textCheckPoint("Received = 0", 1)
    PC_BG.close()
    
    Tablet_PC2.select()
    Tablet_PC2.clickDesktopTab()
    Tablet_PC2.desktop.applications.commandPrompt()
    Tablet_PC2.desktop.commandPrompt.setText("ping 192.168.0.1")
    util.fastForwardTime()
    util.fastForwardTime()
    Tablet_PC2.desktop.commandPrompt.textCheckPoint("Received = 0", 1)
    Tablet_PC2.close()
    
    Pda1.select()
    Pda1.clickDesktopTab()
    Pda1.desktop.applications.commandPrompt()
    Pda1.desktop.commandPrompt.setText("ping 192.168.0.1")
    util.fastForwardTime()
    util.fastForwardTime()
    Pda1.desktop.commandPrompt.textCheckPoint("Received = 0", 1)
    Pda1.close()
    
def permit_PC_BG():
    wirelessRouter0.select()
    wirelessRouter0.gui.tabs.wireless()
    wirelessRouter0.gui.tabs.wirelessMacFilter()
    wirelessRouter0.gui.wireless.macFilter.removeMac(1)
    wirelessRouter0.gui.wireless.macFilter.removeMac(2)
    wirelessRouter0.gui.wireless.macFilter.removeMac(3)
    wirelessRouter0.gui.wireless.macFilter.removeMac(4)
    wirelessRouter0.gui.wireless.macFilter.removeMac(5)
    wirelessRouter0.gui.wireless.macFilter.saveSettingsButton()
    wirelessRouter0.close()
    
    Linksys_WMP300N.select()
    Linksys_WMP300N.desktop.applications.commandPrompt()
    Linksys_WMP300N.desktop.commandPrompt.setText("ping 192.168.0.1")
    util.fastForwardTime()
    util.fastForwardTime()
    Linksys_WMP300N.desktop.commandPrompt.textCheckPoint("Received = 0", 2)
    Linksys_WMP300N.close()
    
    PC_BG.select()
    PC_BG.desktop.applications.commandPrompt()
    PC_BG.desktop.commandPrompt.setText("ping 192.168.0.1")
    util.fastForwardTime()
    util.fastForwardTime()
    PC_BG.desktop.commandPrompt.textCheckPoint("Received = 0", 1)
    PC_BG.close()
    
    Tablet_PC2.select()
    Tablet_PC2.desktop.applications.commandPrompt()
    Tablet_PC2.desktop.commandPrompt.setText("ping 192.168.0.1")
    util.fastForwardTime()
    util.fastForwardTime()
    Tablet_PC2.desktop.commandPrompt.textCheckPoint("Received = 0", 2)
    Tablet_PC2.close()
    
    Pda1.select()
    Pda1.desktop.applications.commandPrompt()
    Pda1.desktop.commandPrompt.setText("ping 192.168.0.1")
    util.fastForwardTime()
    util.fastForwardTime()
    Pda1.desktop.commandPrompt.textCheckPoint("Received = 0", 2)
    Pda1.close()
    
def prevent_PC_BG():
    wirelessRouter0.select()
    wirelessRouter0.gui.tabs.wireless()
    wirelessRouter0.gui.tabs.wirelessMacFilter()
    wirelessRouter0.gui.wireless.macFilter.preventPcsListed()
    wirelessRouter0.gui.wireless.macFilter.saveSettingsButton()
    wirelessRouter0.close()
    
    Linksys_WMP300N.select()
    Linksys_WMP300N.desktop.applications.commandPrompt()
    Linksys_WMP300N.desktop.commandPrompt.setText("ping 192.168.0.1")
    util.fastForwardTime()
    util.fastForwardTime()
    Linksys_WMP300N.desktop.commandPrompt.textCheckPoint("Received = 0", 2)
    Linksys_WMP300N.close()
    
    PC_BG.select()
    PC_BG.desktop.applications.commandPrompt()
    PC_BG.desktop.commandPrompt.setText("ping 192.168.0.1")
    util.fastForwardTime()
    util.fastForwardTime()
    PC_BG.desktop.commandPrompt.textCheckPoint("Received = 0", 2)
    PC_BG.close()
    
    Tablet_PC2.select()
    Tablet_PC2.desktop.applications.commandPrompt()
    Tablet_PC2.desktop.commandPrompt.setText("ping 192.168.0.1")
    util.fastForwardTime()
    util.fastForwardTime()
    Tablet_PC2.desktop.commandPrompt.textCheckPoint("Received = 0", 2)
    Tablet_PC2.close()
    
    Pda1.select()
    Pda1.desktop.applications.commandPrompt()
    Pda1.desktop.commandPrompt.setText("ping 192.168.0.1")
    util.fastForwardTime()
    util.fastForwardTime()
    Pda1.desktop.commandPrompt.textCheckPoint("Received = 0", 2)
    Pda1.close()
    
def disable_Mac():
    wirelessRouter0.select()
    wirelessRouter0.gui.tabs.wireless()
    wirelessRouter0.gui.tabs.wirelessMacFilter()
    wirelessRouter0.gui.wireless.macFilter.disabled()
    wirelessRouter0.gui.wireless.macFilter.saveSettingsButton()
    wirelessRouter0.close()
    
    Linksys_WMP300N.select()
    Linksys_WMP300N.desktop.applications.commandPrompt()
    Linksys_WMP300N.desktop.commandPrompt.setText("ping 192.168.0.1")
    util.fastForwardTime()
    util.fastForwardTime()
    Linksys_WMP300N.desktop.commandPrompt.textCheckPoint("Received = 0", 2)
    Linksys_WMP300N.close()
    
    PC_BG.select()
    PC_BG.desktop.applications.commandPrompt()
    PC_BG.desktop.commandPrompt.setText("ping 192.168.0.1")
    util.fastForwardTime()
    util.fastForwardTime()
    PC_BG.desktop.commandPrompt.textCheckPoint("Received = 0", 2)
    PC_BG.close()

    
    Tablet_PC2.select()
    Tablet_PC2.desktop.applications.commandPrompt()
    Tablet_PC2.desktop.commandPrompt.setText("ping 192.168.0.1")
    util.fastForwardTime()
    util.fastForwardTime()
    Tablet_PC2.desktop.commandPrompt.textCheckPoint("Received = 0", 2)
    Tablet_PC2.close()
    
    Pda1.select()
    Pda1.desktop.applications.commandPrompt()
    Pda1.desktop.commandPrompt.setText("ping 192.168.0.1")
    util.fastForwardTime()
    util.fastForwardTime()
    Pda1.desktop.commandPrompt.textCheckPoint("Received = 0", 2)
    Pda1.close()